# Constants for the tokenizer class

REMOVE_TOKENS = {
        '\'': True,
        '\\':True,
        '-': True,
        '.': True,
        ',': True,
        '\"': True,
        ' ': True,
        ')': True,
        '(': True,
        '{': True,
        '}': True,
        '[': True,
        ']': True,
        '!': True,
        '#': True,
        '@': True,
        '%': True,
        '$': True,
        '*': True,
        'and': True,
        'the': True,
        'or': True,
        'at': True,
        }
